branches:
  only:
      - master
      - code_refactor_2020.01

matrix:
  fast_finish: true
  include:
    - language: java
      jdk: openjdk8
      os: linux
      sudo: required
      after_success:
        - bash <(curl -s https://codecov.io/bash)

    - language: java
      jdk: openjdk9
      os: linux
      sudo: required

    - language: java
      jdk: openjdk10
      os: linux
      sudo: required

    - language: java
      jdk: openjdk11
      os: linux
      sudo: required

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_script:
  - mv config/contract_example config/contract
  - chmod +x gradlew

script:
  - ./gradlew test bootJar

after_success:
  - bash <(curl -s https://codecov.io/bash)
